experiment_dir: PLACEHOLDER
n_forward_steps: 40  # 10 days
forward_steps_in_memory: 40
checkpoint_path: PLACEHOLDER
logging:
  log_to_screen: true
  log_to_wandb: true
  log_to_file: true
  project: ace-example
  wandb_dir_in_experiment_dir: true
loader:
  dataset:
    data_path: /scratch4/GFDL/gfdlscr/Spencer.Clark/public-data/ERA5/netCDFs
  start_indices:
    times:
    - "2020-01-01T00:00:00"
    - "2020-02-01T00:00:00"
    - "2020-03-01T00:00:00"
    - "2020-04-01T00:00:00"
    - "2020-05-01T00:00:00"
    - "2020-06-01T00:00:00"
    - "2020-07-01T00:00:00"
    - "2020-08-01T00:00:00"
    - "2020-09-01T00:00:00"
    - "2020-10-01T00:00:00"
    - "2020-11-01T00:00:00"
    - "2020-12-01T00:00:00"
  num_data_workers: 1
data_writer:
  save_prediction_files: true
  save_monthly_files: false
  time_coarsen:
    coarsen_factor: 4  # Save daily-mean diagnostics
  names:
  - h500
  - PRATEsfc
  - TMP2m
