experiment_dir: PLACEHOLDER
save_checkpoint: true
validate_using_ema: true
ema:
  decay: 0.999
max_epochs: 120
n_forward_steps: 2
train_loader:
  batch_size: 16
  num_data_workers: 4
  prefetch_factor: 4
  dataset:
    - data_path: /scratch4/GFDL/gfdlscr/Spencer.Clark/public-data/ERA5/netCDFs
      subset:
        stop_time: "1995-12-31"
    - data_path: /scratch4/GFDL/gfdlscr/Spencer.Clark/public-data/ERA5/netCDFs
      subset:
        start_time: "2011-01-01"
        stop_time: "2019-12-31"
    - data_path: /scratch4/GFDL/gfdlscr/Spencer.Clark/public-data/ERA5/netCDFs
      subset:
        start_time: "2021-01-01"
validation_loader:
  batch_size: 128
  num_data_workers: 4
  prefetch_factor: 4
  dataset:
    - data_path: /scratch4/GFDL/gfdlscr/Spencer.Clark/public-data/ERA5/netCDFs
      subset:
        start_time: "1996-01-01"
        stop_time: "1997-12-31"
inference:
  n_forward_steps: 7300
  forward_steps_in_memory: 40
  loader:
    start_indices:
      times:
        - "1996-01-01T00:00:00"
        - "1996-02-15T00:00:00"
        - "1996-04-01T00:00:00"
        - "1996-05-15T00:00:00"
        - "1996-07-01T00:00:00"
        - "1996-08-15T00:00:00"
        - "1996-10-01T00:00:00"
        - "1996-11-15T00:00:00"
    dataset:
      data_path: /scratch4/GFDL/gfdlscr/Spencer.Clark/public-data/ERA5/netCDFs
    num_data_workers: 1
  aggregator:
    log_histograms: true
    time_mean_reference_data: /scratch4/GFDL/gfdlscr/Spencer.Clark/public-data/ERA5/stats/time-mean.nc
logging:
  project: ace-example
  wandb_dir_in_experiment_dir: true
optimization:
  enable_automatic_mixed_precision: false
  lr: 0.0001
  optimizer_type: FusedAdam
  kwargs:
    weight_decay: 0.01
stepper:
  builder:
    type: SphericalFourierNeuralOperatorNet
    config:
      embed_dim: 384
      filter_type: linear
      hard_thresholding_fraction: 1.0
      use_mlp: true
      normalization_layer: instance_norm
      num_layers: 8
      operator_type: dhconv
      scale_factor: 1
      separable: false
      spectral_layers: 3
      spectral_transform: sht
      pos_embed: true
  loss:
    type: MSE
    weights:
      air_temperature_0: 0.5
      air_temperature_1: 0.5
      eastward_wind_0: 0.5
      northward_wind_0: 0.5
      specific_total_water_0: 0.5
      specific_total_water_1: 0.25
      specific_total_water_2: 0.5
      PRATEsfc: 0.5
      h500: 10
      TMP850: 5
      Q2m: 0.5
      DLWRFsfc: 2
      ULWRFsfc: 5
      USWRFsfc: 2
      DSWRFsfc: 2
      USWRFtoa: 2
      tendency_of_total_water_path_due_to_advection: 0.5
  normalization:
    global_means_path: /scratch4/GFDL/gfdlscr/Spencer.Clark/public-data/ERA5/stats/centering.nc
    global_stds_path: /scratch4/GFDL/gfdlscr/Spencer.Clark/public-data/ERA5/stats/scaling-full-field.nc
  residual_normalization:
    global_means_path: /scratch4/GFDL/gfdlscr/Spencer.Clark/public-data/ERA5/stats/centering.nc
    global_stds_path: /scratch4/GFDL/gfdlscr/Spencer.Clark/public-data/ERA5/stats/scaling-residual.nc
  ocean:
    surface_temperature_name: surface_temperature
    ocean_fraction_name: ocean_fraction
  corrector:
    conserve_dry_air: true
    moisture_budget_correction: advection_and_precipitation
    force_positive_names:
    - specific_total_water_0
    - specific_total_water_1
    - specific_total_water_2
    - specific_total_water_3
    - specific_total_water_4
    - specific_total_water_5
    - specific_total_water_6
    - specific_total_water_7
    - Q2m
    - PRATEsfc
    - ULWRFsfc
    - ULWRFtoa
    - DLWRFsfc
    - DSWRFsfc
    - USWRFsfc
    - USWRFtoa
  next_step_forcing_names:
  - DSWRFtoa
  in_names:
  - land_fraction
  - ocean_fraction
  - sea_ice_fraction
  - DSWRFtoa
  - HGTsfc
  - global_mean_co2
  - PRESsfc
  - surface_temperature
  - TMP2m
  - Q2m
  - UGRD10m
  - VGRD10m
  - air_temperature_0
  - air_temperature_1
  - air_temperature_2
  - air_temperature_3
  - air_temperature_4
  - air_temperature_5
  - air_temperature_6
  - air_temperature_7
  - specific_total_water_0
  - specific_total_water_1
  - specific_total_water_2
  - specific_total_water_3
  - specific_total_water_4
  - specific_total_water_5
  - specific_total_water_6
  - specific_total_water_7
  - eastward_wind_0
  - eastward_wind_1
  - eastward_wind_2
  - eastward_wind_3
  - eastward_wind_4
  - eastward_wind_5
  - eastward_wind_6
  - eastward_wind_7
  - northward_wind_0
  - northward_wind_1
  - northward_wind_2
  - northward_wind_3
  - northward_wind_4
  - northward_wind_5
  - northward_wind_6
  - northward_wind_7
  out_names:
  - PRESsfc
  - surface_temperature
  - air_temperature_0
  - air_temperature_1
  - air_temperature_2
  - air_temperature_3
  - air_temperature_4
  - air_temperature_5
  - air_temperature_6
  - air_temperature_7
  - specific_total_water_0
  - specific_total_water_1
  - specific_total_water_2
  - specific_total_water_3
  - specific_total_water_4
  - specific_total_water_5
  - specific_total_water_6
  - specific_total_water_7
  - eastward_wind_0
  - eastward_wind_1
  - eastward_wind_2
  - eastward_wind_3
  - eastward_wind_4
  - eastward_wind_5
  - eastward_wind_6
  - eastward_wind_7
  - northward_wind_0
  - northward_wind_1
  - northward_wind_2
  - northward_wind_3
  - northward_wind_4
  - northward_wind_5
  - northward_wind_6
  - northward_wind_7
  - LHTFLsfc
  - SHTFLsfc
  - PRATEsfc
  - ULWRFsfc
  - ULWRFtoa
  - DLWRFsfc
  - DSWRFsfc
  - USWRFsfc
  - USWRFtoa
  - tendency_of_total_water_path_due_to_advection
  - TMP850
  - h500
  - TMP2m
  - Q2m
  - UGRD10m
  - VGRD10m
